---
baseURL: https://icbnews.net
languageCode: en-us
timeZone: Africa/Nairobi
title: ICBN
theme: PaperMod
defaultTheme: auto
googleAnalytics: ''
Params:
  ShowReadingTime: true
  linkFullImages: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  showShareButtons: true
  ShowPostNavLinks: true
  socialIcons:
  - name: instagram
    url: https://www.instagram.com/bunniestore.ke/
  - name: github
    url: https://github.com/tito-arch
  - name: linkedin
    url: https://www.linkedin.com/company/bunnie-abc/

menu:
  main:
  - identifier: Beginner's guide
    name: Beginner's guide
    url: "/categories/beginners-guide/"
    weight: 10
  - identifier: Breaking News
    name: Breaking News
    url: "/categories/breaking-news/"
    weight: 20
  - identifier: Fight News
    name: Fight News
    url: "/categories/fight-news/"
    weight: 30  
  - identifier: I.C.B.N Profiles
    name: I.C.B.N Profiles
    url: "/categories/i.c.b.n-profiles/"
    weight: 40  
  - identifier: Upcoming Events
    name: Upcoming Events
    url: "/categories/upcoming-events/"
    weight: 50   
  - identifier: Rankings
    name: Rankings
    url: "/rankings/"
    weight: 60     
  - identifier: About Us
    name: About Us
    url: "/about/"
    weight: 70         
