---
baseURL: https://icbnews.net
languageCode: en-us
timeZone: Africa/Nairobi
title: ICBN
theme: PaperMod
defaultTheme: auto
googleAnalytics: ''
Params:
  ShowReadingTime: true
  linkFullImages: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  showShareButtons: true
  ShowPostNavLinks: true
  socialIcons:
  - name: instagram
    url: https://www.instagram.com/bunniestore.ke/
  - name: github
    url: https://github.com/tito-arch
  - name: linkedin
    url: https://www.linkedin.com/company/bunnie-abc/
menu:
  main:
  - url: https://icbnews.net/tags/rankings/
    name: Rankings
    weight: 4
  - url: "/archives/"
    name: Archives
    weight: 3
    identifier: archives
  - url: "/tags/"
    name: Tags
    weight: 2
    identifier: tags
  - url: "/categories/"
    name: Categories
    weight: 1
    identifier: categories
