backend:
  name: git-gateway
  branch: master
logo_url: https://ke.bunnieabc.com/static/media/bunnieframe.37862a2101c816b46583.jpeg
site_url: https://icbnews.net
display_url: https://icbnews.net
publish_mode: simple # Enable saving drafts and editing
media_folder: "/static/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"
editor:
  preview: false
  frame: false
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}"
    media_folder: "/static/uploads" # Folder where user uploaded files should go
    public_folder: "/uploads"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Title", name: "title", widget: "string", config: { required: true, min: 10, max: 67 }, description: "Enter the Article's title." }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Photo", name: "image", widget: "image", hint: "All images should have an alt text.", default: "bunnie abc" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false, default: true, hint: "If turned on, this post will not be visible to the public." }
      - { label: "Category", name: "category", widget: "select", options: ["Artificial Intelligence & Machine Learning", "App Updates", "Computer Science", "Blockchain & Web3", "Device Reviews", "Emerging Issues & Trends"], required: true }
      - { label: "Author", name: "author", widget: "select", options: ["BABC", "M.I.Titus", "P.Gitau", "B.Wamaitha"], required: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
